### ISSUE TITLE
Problem report

### ISSUE THREAD

**Issue by joelmccracken** [pittsburgh-haskell/haskell-installation#2]
I had some problems using cabal; here's the log and how I fixed it:

```
○ → brew install cabal-install
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/cabal-install-1.22.0.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/cabal-install-1.22.0.0.yosemite.bottle.tar.gz
==> Pouring cabal-install-1.22.0.0.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.22.0.0: 6 files, 23M

57  JoelMcCckensMBP in ~
○ → cabal update 
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/bin/cabal
  Reason: image not found
Trace/BPT trap: 5

57  JoelMcCckensMBP in ~
○ → brew list | grep gmp
gmp

57  JoelMcCckensMBP in ~
○ → brew uninstall gmp
Uninstalling /usr/local/Cellar/gmp/6.0.0a...
gmp 5.0.5, 5.1.2, 5.1.3 are still installed.
Remove them all with `brew uninstall --force gmp`.

57  JoelMcCckensMBP in ~
○ → brew uninstall --force gmp
Uninstalling gmp...

57  JoelMcCckensMBP in ~
○ → brew install gmp
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gmp-6.0.0a.yosemite.bottle.tar.gz
################################################################################################################################################################################################## 100.0%
==> Pouring gmp-6.0.0a.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.0.0a: 15 files, 3.2M

57  JoelMcCckensMBP in ~
○ → cabal update                                                                                                                                                                                  
Config file path source is default config file.
Config file /Users/joel/.cabal/config not found.
Writing default configuration to /Users/joel/.cabal/config
Downloading the latest package list from hackage.haskell.org
^[v
```

**Comment by FranklinChen** [comment]
Yeah, there are mysterious `gmp` issues that have popped up in various contexts. Having an old version would be one cause. Although I ran into another one that should not happen in the workshop, but came up at work where I did a clean install of everything! I found a workaround:

https://github.com/Homebrew/homebrew/issues/35203

**Comment by briancavalier** [comment]
I don't know if this is the same problem, but I had some stale files from an older ghc/cabal hanging out in ~/.cabal and ~/.ghc.  It seemed to cause some really weird issues trying to install packages and newer versions of ghc/cabal.  I uninstalled ghc and cabal, clobbered ~/.cabal and ~/.ghc, then reinstalled both ghc and cabal.

**Comment by FranklinChen** [comment]
Yeah, we found out tonight that many people had old directories lying around, and had them remove `~/.cabal` and `~/.ghc`. I will update my instructions to warn about this possibility.

**Comment by FranklinChen** [comment]
I added instructions about checking versions and removing old stuff. https://github.com/pittsburgh-haskell/haskell-installation/commits/master

**Comment by FranklinChen** [comment]
I added instructions about removal of old directories. https://github.com/pittsburgh-haskell/haskell-installation/commit/65560326602aaf066c2daf6efb281ac9249c4f8c

**Comment by briancavalier** [comment]
+1 Thanks!

**Comment by FranklinChen** [comment]
At long last, a solution to the mystery of `gmp` (and other failures):

https://github.com/Homebrew/homebrew/issues/35203

```
xcode-select --install
```

was the real fix.

**Comment by briancavalier** [comment]
Great to know, thanks @FranklinChen.
